apiVersion: apps/v1
kind: Deployment
metadata: 
  name:  plain-deploy
  namespace: demo
  labels:
    app:  plain-deploy-app
spec:
  selector:
    matchLabels:
      app: plain-deploy-app
  replicas: 2
  template:
    metadata:
      labels:
        app:  plain-deploy-app
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  plain-deploy-app-container
        image:  nginx:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  80