apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80 # assume equal value to port if not provided
    nodePort: 30008 # 30000~32767, randomly selected if not provided
  selector:
    app: myapp
    type: front-end