apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod 
  labels:
    app: myapp
    type: front-end
spec:
  containers:
    - name: nginx-containers
      image: nginx
      resources:
        requests:
          cpu: "1"
          memory: 250Mi
        limits:
          cpu: "10"
          memory: 10Gi
