apiVersion: v1
kind: Pod
metadata:
  name: simple-color-web
  labels:
    name: simple-color-web
spec:
  containers:
  - name: simple-color-web
    image: mmumshad/simple-webapp-color
    ports:
      - containerPort: 8080
    envFrom:
      - configMapRef:
          name: app-config
