apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper
  labels:
    name: ubuntu-sleeper-app
spec:
  containers:
  - name: ubuntu-sleeper-app
    image: youngstone89/ubuntu-sleeper:v1
    args: ["10"]
    resources:
      limits:
        memory: "50Mi"
        cpu: "100m"
