apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::773757336212:role/spotinst-eks-stack-NodeInstanceRole-1SLGNOWU8H4OJ
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::773757336212:user/edward.lee@bespinglobal.com
      username: edward.lee@bespinglobal.com
      groups:
        - system:masters