apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: krypton-router-ingress
    annotations:
        kubernetes.io/ingress.class: nuance-coretech
        ingress.kubernetes.io/ssl-passthrough: "true"
spec:
    rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: krypton-router
              port:
                number: 8090