apiVersion: apps/v1
kind: Deployment
metadata:
  name:  custom-label-lifecycle-od
  namespace: demo
  labels:
    app:  custom-label-lifecycle-od
spec:
  selector:
    matchLabels:
      app: custom-label-lifecycle-od
  replicas: 1
  template:
    metadata:
      labels:
        app:  custom-label-lifecycle-od
        spotinst.io/restrict-scale-down: 'true' #Prevent AutoScaler to scale down nodes on which pods with this lable are running.
    spec:
      containers:
      - name:  custom-label-lifecycle-od-app-container
        image:  nginx:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
      nodeSelector:
        spotinst.io/node-lifecycle: od