apiVersion: apps/v1
kind: Deployment
metadata:
  name:  custom-label-lifecycle-od
  namespace: demo
  labels:
    app:  custom-label-lifecycle-od
spec:
  selector:
    matchLabels:
      app: custom-label-lifecycle-od
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  custom-label-lifecycle-od
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  custom-label-lifecycle-od-app-container
        image:  nginx:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
      nodeSelector:
        spotinst.io/node-lifecycle: od