apiVersion: v1
kind: Pod
metadata:
  name: mysql-pvc-pod
spec:
  containers:
    - name: mysql
      image: mysql:5.6
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: mysql!@#$
      ports:
        - containerPort: 3306
          name: mysql
      volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: mysql-hostpath-storage
  volumes:
    - name: mysql-hostpath-storage
      persistentVolumeClaim:
        claimName: mysql-hostpath-pv-pvc


